export const Tech = [
  { title: 'React JS' },
  { title: 'Vue JS' },
  { title: 'Angular JS' },
  { title: 'Jquery' },
  { title: 'Vanilla JS' },
  { title: "Node Js" },
  { title: 'Express' },
  { title: 'Typescript' },
  { title: "Javascript" },
  { title: 'GraphQL' },
  { title: 'MongoDB' },
  { title: 'HTML' },
  { title: 'CSS' },
  { title: 'SCSS' },
  { title: 'Tailwind' },
  { title: 'JSS' },
];